import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex space-x-3 absolute top-5 left-5 text-lg">
          <Link className="border border-black px-4 py-2" href="/">
            Flash Cards
          </Link>
          <Link className="border border-black px-4 py-2" href="/topics">
            Lessons
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
